apiVersion: apps/v1
kind: Deployment
metadata:
  name: lab-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: lab-app
  template:
    metadata:
      labels:
        app: lab-app
    spec:
      containers:
      - name: lab-app
        image: lab-app:production-build
        ports:
        - containerPort: 3000
